USE StarDeck
DELETE FROM CartasXTurnoXDeckXUsuario
DELETE FROM CartasXTurnoXManoXUsuario
DELETE FROM CartasXTurnoXPlanetaXUsuario
DELETE FROM PlanetasXPartida
DELETE FROM UsuarioXPartida
DELETE FROM TurnoXUsuario
DELETE FROM Partida